SERVER RUNNING ON PORT 80
{
  push_data: { pushed_at: 1610698257, images: [], tag: 'latest', pusher: 's4ng' },
  callback_url: 'https://registry.hub.docker.com/u/s4ng/cicd-dino/hook/2ab3i2ahh1ai34heaea3d4b34ha21d1hb/',
  repository: {
    status: 'Active',
    description: '',
    is_trusted: false,
    full_description: null,
    repo_url: 'https://hub.docker.com/r/s4ng/cicd-dino',
    owner: 's4ng',
    is_official: false,
    is_private: false,
    name: 'cicd-dino',
    namespace: 's4ng',
    star_count: 0,
    comment_count: 0,
    date_created: 1610495333,
    repo_name: 's4ng/cicd-dino'
  }
}
Using default tag: latest
latest: Pulling from s4ng/cicd-dino
2587235a7635: Already exists
953fe5c215cb: Already exists
d4d3f270c7de: Already exists
ed36dafe30e3: Already exists
00e912dd434d: Already exists
dd25ee3ea38e: Already exists
7e835b17ced9: Already exists
79ae84aa9e91: Already exists
629164f2c016: Already exists
0c9112cb458e: Pulling fs layer
6c5e56e21d71: Pulling fs layer
37ef89fe012a: Pulling fs layer
0c9112cb458e: Download complete
0c9112cb458e: Pull complete
6c5e56e21d71: Download complete
6c5e56e21d71: Pull complete
37ef89fe012a: Verifying Checksum
37ef89fe012a: Download complete
37ef89fe012a: Pull complete
Digest: sha256:ab7eba7a5f5aa441846dcd0582b0f38ee98e7002c8a4a5ab054d4e9da941e9ba
Status: Downloaded newer image for s4ng/cicd-dino:latest
docker.io/s4ng/cicd-dino:latest
docker: Error response from daemon: Conflict. The container name "/cicdapp" is already in use by container "4bc7b53efca89b6a45906136a92611e9e41a470ca56c5f828a2976e34dd3b30f". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
{
  push_data: { pushed_at: 1610698609, images: [], tag: 'latest', pusher: 's4ng' },
  callback_url: 'https://registry.hub.docker.com/u/s4ng/cicd-dino/hook/2230ahegid2d045bjdcdccg4d044f4eae/',
  repository: {
    status: 'Active',
    description: '',
    is_trusted: false,
    full_description: null,
    repo_url: 'https://hub.docker.com/r/s4ng/cicd-dino',
    owner: 's4ng',
    is_official: false,
    is_private: false,
    name: 'cicd-dino',
    namespace: 's4ng',
    star_count: 0,
    comment_count: 0,
    date_created: 1610495333,
    repo_name: 's4ng/cicd-dino'
  }
}
Using default tag: latest
latest: Pulling from s4ng/cicd-dino
2587235a7635: Already exists
953fe5c215cb: Already exists
d4d3f270c7de: Already exists
ed36dafe30e3: Already exists
00e912dd434d: Already exists
dd25ee3ea38e: Already exists
7e835b17ced9: Already exists
79ae84aa9e91: Already exists
629164f2c016: Already exists
449238db15ea: Pulling fs layer
597b413859ed: Pulling fs layer
841fba0949b7: Pulling fs layer
449238db15ea: Verifying Checksum
449238db15ea: Download complete
449238db15ea: Pull complete
597b413859ed: Verifying Checksum
597b413859ed: Download complete
597b413859ed: Pull complete
841fba0949b7: Verifying Checksum
841fba0949b7: Download complete
841fba0949b7: Pull complete
Digest: sha256:f36bb503da3b0aa589c43a1a0e6aa66212137ca7c4b0ff9f633e2b8103d99d29
Status: Downloaded newer image for s4ng/cicd-dino:latest
docker.io/s4ng/cicd-dino:latest
docker: Error response from daemon: Conflict. The container name "/cicdapp" is already in use by container "4bc7b53efca89b6a45906136a92611e9e41a470ca56c5f828a2976e34dd3b30f". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
